;; pb1-classical, with the missing longDistance facts asserted.
;; Every pair of locations in different cities is far apart, in both directions,
;; which is what the HTN methods were quietly assuming and the actions never said.
(define (problem pb1-classical-fixed)
  (:domain travel-classical)
  (:objects portoalegre saopaulo london poa gru lhr)
  (:init (at portoalegre)
         (airport poa portoalegre) (airport gru saopaulo) (airport lhr london)
         (longDistance portoalegre saopaulo)
         (longDistance portoalegre london)
         (longDistance portoalegre gru)
         (longDistance portoalegre lhr)
         (longDistance saopaulo portoalegre)
         (longDistance saopaulo london)
         (longDistance saopaulo poa)
         (longDistance saopaulo lhr)
         (longDistance london portoalegre)
         (longDistance london saopaulo)
         (longDistance london poa)
         (longDistance london gru)
         (longDistance poa saopaulo)
         (longDistance poa london)
         (longDistance poa gru)
         (longDistance poa lhr)
         (longDistance gru portoalegre)
         (longDistance gru london)
         (longDistance gru poa)
         (longDistance gru lhr)
         (longDistance lhr portoalegre)
         (longDistance lhr saopaulo)
         (longDistance lhr poa)
         (longDistance lhr gru)
  )
  (:goal (at saopaulo))
)
